version: '3.1'

services:

  postgres:
    image: postgres:12.1-alpine
    container_name: PostgresDB
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

  api-server:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: API-server
    restart: always
    ports:
      - 5000:5000
    links:
      - postgres:postgres
  
volumes:
  db-data:
